version: '3.7'

services:
  dbc_client:
    hostname: dbc_client
    image: nginx:latest
    ports:
      - "8011:80"
    volumes:
      - ./client/code:/code
      - ./client/config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kong-net

  php:
    image: php:fpm-alpine
    volumes:
      - ./client/code:/code
    networks:
      - kong-net