version: '3.7'

services:
  dbc_client:
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes: 
      - ./client/code:/code
      - ./client/config/site.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php
    networks: 
      - kong-net  

  php:
    image: php:fpm-alpine
    volumes: 
      - ./client/code:/code
    networks: 
      - kong-net