version: '3.7'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    container_name: cms.db.ghost
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - kong-net      
  ghost:
    image: 'docker.io/bitnami/ghost:3-debian-10'
    container_name: cms.ghost
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=localhost
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - kong-net
  integration-proxy:
    image: 'moti.bc.ca/internal-cms-proxy'
    container_name: moti.bc.ca-cms.integration.proxy
    ports:
      - 9877:8877
    depends_on:
      - ghost
    environment:
      - GHOST_SERVER_HOST=ghost:2368
    networks:
      - kong-net
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local