- module: mongodb
  period: 10s
  enabled: true
  metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]

  # The hosts must be passed as MongoDB URLs in the format:
  # [mongodb://][user:pass@]host[:port].
  # The username and password can also be set using the respective configuration
  # options. The credentials in the URL take precedence over the username and
  # password configuration options.
  hosts: ["mongodb://beats:pass@mongodb:27017"]

  # Username to use when connecting to MongoDB. Empty by default.
  #username: beats

  # Password to use when connecting to MongoDB. Empty by default.
  #password: pass